server:
  port: 9090

spring:
  application:
    name: telegrambotapp
  datasource:
    url: jdbc:postgresql://localhost:5432/tinkofftelegramdb
    username: postgres
    password: ld2erw71904
    driver-class-name: org.postgresql.Driver